name: Build/release artifacts

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Build Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update && sudo apt install libudev-dev libusb-1.0-0-dev
          npm i
          npm run build-linux


      - name: Build Macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          npm i
          npm run build-macwin

      # - name: Build/release
      #   uses: samuelmeuli/action-electron-builder@v1
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     release: ${{ startsWith(github.ref, 'refs/tags/v') }}
